version: "3.9"

services:
  backend:
    build: .
    image: buzzatt-backend:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/buzzatt
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buzzatt
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d buzzatt"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  db_data:
