version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/buzzatt
      - SECRET_KEY=your-secret-key-for-testing
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=buzzatt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
